-- =============================================================================
-- 02_reset_schema.sql
-- UTILITY SCRIPT — NOT run automatically on first startup.
-- Use this manually to wipe the GESTIONALE_OWNER schema and let Flyway
-- re-run all migrations from scratch.
--
-- Run as GESTIONALE_OWNER:
--   sqlplus GESTIONALE_OWNER/password@//localhost:1521/FREEPDB1 @02_reset_schema.sql
-- =============================================================================

-- 1. Drop all application tables (order respects foreign keys)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUCT CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_ROLES CASCADE CONSTRAINTS';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROLES CASCADE CONSTRAINTS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 2. Drop Flyway history (forces full re-migration)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FLYWAY_SCHEMA_HISTORY';            EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 3. Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CUSTOMERS_SEQ';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUCTS_SEQ';                  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORDERS_SEQ';                    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORDER_ITEMS_SEQ';               EXCEPTION WHEN OTHERS THEN NULL; END;
/
