server:
  port: 8084 # Porta specifica per il UI Service

spring:
  application:
    name: ui-service
  thymeleaf:
    cache: false # Disabilita la cache di Thymeleaf per lo sviluppo (per vedere subito le modifiche)
    prefix: classpath:/templates/ # Percorso delle pagine HTML
    suffix: .html # Suffisso dei file template

api:
  gateway:
    url: http://localhost:8080 # L'URL del nostro API Gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Indirizzo dell'Eureka Server