spring.application.name=eureka-server

port: 8761 # Porta di default per Eureka Server

spring:
application:
name: eureka-server

eureka:
client:
# Non registrare l'Eureka Server come client di se stesso
register-with-eureka: false
fetch-registry: false
server:
# Opzionale: pulizia rapida per test in locale, non usare in prod
eviction-interval-timer-in-ms: 5000