-- Eseguire come SYSTEM o SYSDBA

-- *** CREAZIONE TABLESAPCE ***
CREATE TABLESPACE SECURITY_TS DATAFILE '/opt/oracle/oradata/XEPDB1/security_ts01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE MANAGEMENT_TS DATAFILE '/opt/oracle/oradata/XEPDB1/management_ts01.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE BATCH_TS DATAFILE '/opt/oracle/oradata/XEPDB1/batch_ts01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;

-- *** CREAZIONE UTENTI E PRIVILEGI DI BASE ***
CREATE USER security_user IDENTIFIED BY "SecurityPass123!" DEFAULT TABLESPACE SECURITY_TS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO security_user;
GRANT RESOURCE TO security_user;
ALTER USER security_user QUOTA UNLIMITED ON SECURITY_TS;

CREATE USER management_user IDENTIFIED BY "ManagePass123!" DEFAULT TABLESPACE MANAGEMENT_TS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO management_user;
GRANT RESOURCE TO management_user;
ALTER USER management_user QUOTA UNLIMITED ON MANAGEMENT_TS;

CREATE USER batch_user IDENTIFIED BY "BatchPass123!" DEFAULT TABLESPACE BATCH_TS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION TO batch_user;
GRANT RESOURCE TO batch_user;
ALTER USER batch_user QUOTA UNLIMITED ON BATCH_TS;

COMMIT;
