-- RESET COMPLETO DELLO SCHEMA GESTIONALE_OWNER

-- 1. Rimuovi tutte le tabelle rilevanti in ordine di dipendenza
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDER_ITEM CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCT CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ROLES CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE USER_ROLES CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE FLYWAY_SCHEMA_HISTORY';
EXCEPTION
    WHEN OTHERS THEN
        NULL; -- ignora errori se la tabella non esiste
END;
/

-- 2. Rimuovi eventuali SEQUENZE (Hibernate usa "CUSTOMERS_SEQ", ecc.)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CUSTOMERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- 3. Rimuovi eventuali indici residui (opzionale, se definiti manualmente)
-- BEGIN
--     EXECUTE IMMEDIATE 'DROP INDEX IDX_CUSTOMER_EMAIL';
-- EXCEPTION
--     WHEN OTHERS THEN
--         NULL;
-- END;
-- /