spring.application.name=batch-service

spring:
application:
name: security-service # O management-service, o batch-service
datasource:
url: jdbc:oracle:thin:@localhost:1521/XEPDB1 # XEPDB1 è il PDB (Pluggable Database) di default in Oracle XE. Potrebbe essere XE in alcune configurazioni.
username: SYSTEM # O un utente DB dedicato che creerai in futuro
password: yourStrongPassword! # La password impostata nel comando docker run
driver-class-name: oracle.jdbc.OracleDriver
jpa:
hibernate:
ddl-auto: update # ATTENZIONE: usare 'update' solo in ambiente di sviluppo! In produzione usare 'none' e gestite le migrazioni con Flyway/Liquibase.
show-sql: true # Mostra le query SQL generate da Hibernate nel log. Utile per il debug.
properties:
format_sql: true # Formatta l'SQL nel log per una migliore leggibilità

eureka:
client:
serviceUrl:
defaultZone: http://localhost:8761/eureka/ # Indirizzo dell'Eureka Server