-- V10__create_sequences.sql
-- Crea le sequence mancanti usate nelle entità Java

-- === CUSTOMER ===
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- ORA-00955: name is already used
      RAISE;
    END IF;
END;
/

-- === PRODUCT ===
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE PRODUCTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- === ORDERS ===
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

-- === ORDER_ITEM ===
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE ORDER_ITEMS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/