-- V11__grant_management_privileges.sql
-- Concede tutti i privilegi sulle tabelle e le sequence di gestione
-- all'utente applicativo MANAGEMENT_USER

-- === TABELLE ===
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTIONALE_OWNER.CUSTOMER     TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTIONALE_OWNER.PRODUCT      TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTIONALE_OWNER.ORDERS       TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTIONALE_OWNER.ORDER_ITEM   TO MANAGEMENT_USER;

-- === SEQUENZE ===
GRANT SELECT ON GESTIONALE_OWNER.CUSTOMERS_SEQ     TO MANAGEMENT_USER;
GRANT SELECT ON GESTIONALE_OWNER.PRODUCTS_SEQ      TO MANAGEMENT_USER;
GRANT SELECT ON GESTIONALE_OWNER.ORDERS_SEQ        TO MANAGEMENT_USER;
GRANT SELECT ON GESTIONALE_OWNER.ORDER_ITEMS_SEQ   TO MANAGEMENT_USER;