ALTER TABLE USERS ADD (
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    ACCOUNT_NON_LOCKED NUMBER(1) DEFAULT 1 NOT NULL,
    FAILED_LOGIN_ATTEMPTS NUMBER DEFAULT 0 NOT NULL,
    LOCKED_UNTIL TIMESTAMP
);
