-- Add audit columns to Customer
ALTER TABLE GESTIONALE_OWNER.CUSTOMER ADD CREATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.CUSTOMER ADD UPDATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.CUSTOMER ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE GESTIONALE_OWNER.CUSTOMER ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add audit columns to Product
ALTER TABLE GESTIONALE_OWNER.PRODUCT ADD CREATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.PRODUCT ADD UPDATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.PRODUCT ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE GESTIONALE_OWNER.PRODUCT ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add audit columns to Orders
ALTER TABLE GESTIONALE_OWNER.ORDERS ADD CREATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.ORDERS ADD UPDATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.ORDERS ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE GESTIONALE_OWNER.ORDERS ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add audit columns to OrderItem
ALTER TABLE GESTIONALE_OWNER.ORDER_ITEM ADD CREATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.ORDER_ITEM ADD UPDATED_BY VARCHAR2(50 CHAR);
ALTER TABLE GESTIONALE_OWNER.ORDER_ITEM ADD CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE GESTIONALE_OWNER.ORDER_ITEM ADD UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
