CREATE TABLE GESTIONALE_OWNER.REFRESH_TOKEN (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOKEN VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    USER_ID NUMBER NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REVOKED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES GESTIONALE_OWNER.USERS(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_REFRESH_TOKEN ON GESTIONALE_OWNER.REFRESH_TOKEN(TOKEN);
GRANT SELECT, INSERT, UPDATE, DELETE ON GESTIONALE_OWNER.REFRESH_TOKEN TO security_user;
