-- V1__create_security_tables.sql

-- Tabella per gli Utenti dell'applicazione
CREATE TABLE APP_USER (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- ID auto-incrementante per Oracle 12c+
    USERNAME VARCHAR2(255) NOT NULL UNIQUE, -- UNIQUE crea già un indice implicito
    PASSWORD VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,    -- UNIQUE crea già un indice implicito
    ACCOUNT_EXPIRED NUMBER(1,0) DEFAULT 0 NOT NULL, -- 0 for false, 1 for true (Boolean-like)
    ACCOUNT_LOCKED NUMBER(1,0) DEFAULT 0 NOT NULL,  -- 0 for false, 1 for true
    CREDENTIALS_EXPIRED NUMBER(1,0) DEFAULT 0 NOT NULL, -- 0 for false, 1 for true
    ENABLED NUMBER(1,0) DEFAULT 1 NOT NULL            -- 0 for false, 1 for true
); -- Aggiungi il punto e virgola, buona pratica per Flyway

-- Tabella per i Ruoli
CREATE TABLE ROLE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- ID auto-incrementante
    NAME VARCHAR2(50) NOT NULL UNIQUE -- UNIQUE crea già un indice implicito
);

-- Tabella di Join per la relazione Many-to-Many tra Utenti e Ruoli
CREATE TABLE USER_ROLES (
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

-- Rimuovi o commenta le seguenti righe, in quanto gli indici sono già creati dalle clausole UNIQUE/PRIMARY KEY
-- CREATE INDEX IDX_APP_USER_USERNAME ON APP_USER (USERNAME);
-- CREATE INDEX IDX_APP_USER_EMAIL ON APP_USER (EMAIL);
-- CREATE INDEX IDX_ROLE_NAME ON ROLE (NAME);