-- V3__grant_permissions_to_security_user.sql

-- Concede i permessi SELECT, INSERT, UPDATE, DELETE all'utente 'security_user'
-- sulle tabelle di proprietà di GESTIONALE_OWNER.
-- Flyway eseguirà questo script come GESTIONALE_OWNER.
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_USER TO security_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLE TO security_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_ROLES TO security_user;

-- Se avessi utilizzato sequenze esplicite (e non GENERATED BY DEFAULT ON NULL AS IDENTITY),
-- avresti dovuto anche concedere il permesso SELECT su di esse:
-- GRANT SELECT ON APP_USER_SEQ TO security_user;
-- GRANT SELECT ON ROLE_SEQ TO security_user;
