-- V3__grant_permissions_to_security_user.sql

-- Grant SELECT, INSERT, UPDATE, DELETE permissions to 'security_user'
-- on tables owned by GESTIONALE_OWNER.
-- Flyway will execute this script as GESTIONALE_OWNER.
GRANT SELECT, INSERT, UPDATE, DELETE ON USERS TO security_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLES TO security_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER_ROLES TO security_user;

-- If you were using explicit sequences (and not GENERATED BY DEFAULT ON NULL AS IDENTITY),
-- you would also need to grant SELECT permission on them:
-- GRANT SELECT ON USERS_SEQ TO security_user;
-- GRANT SELECT ON ROLES_SEQ TO security_user;