-- Inserimento prodotti iniziali
INSERT INTO PRODUCT (NAME, PRICE, STOCK_QUANTITY) VALUES ('Laptop', 899.99, 10);
INSERT INTO PRODUCT (NAME, PRICE, STOCK_QUANTITY) VALUES ('Smartphone', 499.90, 25);
INSERT INTO PRODUCT (NAME, PRICE, STOCK_QUANTITY) VALUES ('Mouse', 25.50, 100);