-- Concessione privilegi all'utente MANAGEMENT_USER
GRANT SELECT, INSERT, UPDATE, DELETE ON CUSTOMER TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCT TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO MANAGEMENT_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDER_ITEM TO MANAGEMENT_USER;